apiVersion: v1
kind: Service
metadata:
  name: homestead
  labels:
    app: homestead
spec:
  ports:
  - name: "8888"
    port: 8888
  selector:
    app: homestead
    service: homestead
  clusterIP: None
