apiVersion: v1
kind: Service
metadata:
  name: homestead-prov
  labels:
    app: homestead-prov
spec:
  ports:
  - name: "8889"
    port: 8889
  selector:
    app: homestead-prov
    service: homestead-prov
  clusterIP: None
